/volunteer
HackMerced/HackMerced-III pull request #16
Opened 2017-07-26 21:06 UTC by JFernandez1995

/volunteer page added

2017-07-26 21:12 UTC, 4shub requested changes
Pls fix

2017-07-26 21:12 UTC, 4shub commented on HackMerced/2017F/src/app/src/components/forms/volunteer.js
> +export class VolForm extends Component {
Can you use full names (VolunteerForm)

2017-07-26 21:12 UTC, 4shub commented on HackMerced/2017F/src/app/src/components/volunteer.js
> +import { VolForm } from './forms';
Same

2017-07-26 21:12 UTC, 4shub commented on HackMerced/2017F/src/app/src/reducers/index.js
> +  avail: '',
use full names please

2017-07-26 21:12 UTC, 4shub commented on HackMerced/2017F/src/app/src/reducers/index.js
> +  diet: '',
call this dietary_restrictions

2017-07-26 21:12 UTC, 4shub commented on HackMerced/2017F/src/app/src/reducers/index.js
> +  size: '',
shirt_size

2017-07-28 05:43 UTC, JFernandez1995 commented
fixed naming conventions for /volunteer

2017-08-30 01:13 UTC, zzmarkzz321 commented
@JFernandez1995 Please fix the merge conflicts

2017-08-30 04:24 UTC, 4shub approved these changes

2017-08-31 02:54 UTC, merged