Volunteer routes
HackMerced/HackMerced-III pull request #29
Opened 2017-09-03 01:34 UTC by Artsyy

I didn't know wether I could use the Hacker validators and handlers but assumed we could.

2017-09-03 01:35 UTC, 4shub commented on HackMerced/2017F/src/server/src/routes/volunteer.js
> +export const postMe = {
remove?

2017-09-05 00:37 UTC, zzmarkzz321 requested changes

2017-09-05 00:37 UTC, zzmarkzz321 commented on HackMerced/2017F/src/server/src/routes/index.js
> +let routes = [
Remove duplicate variable and move inside of one

2017-09-05 00:37 UTC, zzmarkzz321 commented on HackMerced/2017F/src/server/src/routes/volunteer.js
> +export const postVolunteer = {
We already have a route for ``` /signup ```, create a new unique route for volunteers. 
ex:
```plaintext
/volunteers/signup
```

2017-09-05 00:37 UTC, zzmarkzz321 commented on HackMerced/2017F/src/server/src/handlers/volunteer.js
> +      .post(TOMOE_URI + '/volunteers', req.payload)
``` /volunteers ``` is not an endpoint. We'll most likely be using hackers and modifying the survey field.

2017-09-05 00:46 UTC, zzmarkzz321 requested changes
Also ``` export * from ./volunteer ``` inside of ``` index.js``` for validators and handlers

2017-09-05 00:46 UTC, zzmarkzz321 commented on HackMerced/2017F/src/server/src/validators/volunteer.js
> +	    	id: Joi.string().required()
indent and close payload json

2017-09-07 02:22 UTC, zzmarkzz321 commented
Looks good; Waiting on me to finish the rest of the back end. Once my PR has been made, we'll merge both at the same time.

2017-09-14 08:35 UTC, zzmarkzz321 approved these changes

2017-09-14 23:46 UTC, merged